### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by krabo0om** [secworks/ChaCha20-Poly1305#1]
Hey,
thanks for sharing your implementation. 
What is the status of this project? Is the core fully functional?

Thanks!

**Comment by secworks** [comment]
Nope. The core is not yet functional. I got stuck on working out the best design for the big multiplier in poly1305 and then got sidetracked by other things including summer vacation.

**Comment by secworks** [comment]
There status info at the bottom of the README. I try to update status info in cores to correspond with the real status.

**Comment by secworks** [comment]
I will try and complete the core during this autumn. Too many unfinished projects right now.
